trigger:
- main

pool:
  name: 'DevopsAgent'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python largest_number.py
  displayName: 'Run largest_number.py'
