trigger:
- main

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
    - script: |
        python -m venv env
        # Windows specific activation
        if [ "$AGENT_OS" == "Windows_NT" ]; then
          env\Scripts\activate
        else
          source env/bin/activate
        fi
      displayName: 'Set up Python environment'

- stage: Test
  dependsOn: Build
  jobs:
  - job: Test
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
    - script: |
        # Activate environment (cross-platform)
        if [ "$AGENT_OS" == "Windows_NT" ]; then
          env\Scripts\activate
        else
          source env/bin/activate
        fi
        python -m unittest discover -s tests
      displayName: 'Run tests'
